### ISSUE TITLE
spurious colon in the header

### ISSUE THREAD

**Issue by u-fischer** [SFr682k/fancyhandout#3]
```
\documentclass{fancyhandout}

\begin{document}
some test
\end{document}
```

shows a lonely colon on the right of the header.

**Comment by SFr682k** [comment]
The problem was that I checked for the wrong commands after switching to short title/author/…  
Should be fixed with the merge commit listed above.

**Comment by tychobrailleur** [comment]
👍 works for me, thanks!

**Comment by u-fischer** [comment]
You should decide if you want to use `\@empty` or `\empty`:

       \ifx\insertshorttitle\@empty\else\ifx\insertshortauthor\empty
